
version: '3.1'
services:
  redis:
    image: redis:alpine
  mongo:
    image: mongo
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

