
version: '3.1'
services:
  redis:
    image: redis:alpine
  mongo:
    image: mongo
  api:
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGODB_ADDON_URI=mongodb://mongo:27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - /code/src/node_modules
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

